/**
 * Dynamic config over app.json: injects build-time values from the
 * environment (EAS reads them from env / secrets). The Google Maps key
 * cannot work in Expo Go — see lib/maps-support.ts — so it is only
 * attached when present. APPLE_TEAM_ID signs the widget extension
 * target generated by @bacons/apple-targets.
 *
 * onDemandFilesystem is off so Metro keeps ../src as a watch folder on
 * `expo export` — with it on, the export drops every watch folder but
 * this one and refuses lazy reads above it, so @shared/ runtime imports
 * (see metro.config.js) fail to resolve. It is a bundler setting with
 * no native effect, so fingerprint.config.js keeps it out of the
 * runtime version.
 */
module.exports = ({ config }) => {
  let next = {
    ...config,
    experiments: { ...config.experiments, onDemandFilesystem: false },
  };
  const teamId = process.env.APPLE_TEAM_ID;
  if (teamId) {
    next = { ...next, ios: { ...next.ios, appleTeamId: teamId } };
  }
  const key = process.env.GOOGLE_MAPS_ANDROID_API_KEY;
  if (key) {
    next = {
      ...next,
      android: {
        ...next.android,
        config: {
          ...(next.android?.config ?? {}),
          googleMaps: { apiKey: key },
        },
      },
    };
  }
  return next;
};
