/**
 * Dynamic config over app.json: injects build-time values from the
 * environment (EAS reads them from env / secrets). The Google Maps key
 * cannot work in Expo Go — see lib/maps-support.ts — so it is only
 * attached when present. APPLE_TEAM_ID signs the widget extension
 * target generated by @bacons/apple-targets.
 */
module.exports = ({ config }) => {
  let next = config;
  const teamId = process.env.APPLE_TEAM_ID;
  if (teamId) {
    next = { ...next, ios: { ...next.ios, appleTeamId: teamId } };
  }
  const key = process.env.GOOGLE_MAPS_ANDROID_API_KEY;
  if (key) {
    next = {
      ...next,
      android: {
        ...next.android,
        config: {
          ...(next.android?.config ?? {}),
          googleMaps: { apiKey: key },
        },
      },
    };
  }
  return next;
};
