import { NextResponse } from 'next/server';
import { requireRole, toErrorResponse } from '@/lib/auth/account';
import { checkPlanLimit, gateResponse } from '@/lib/billing/gates';
import { burnCredits, refundCredits } from '@/lib/credits/burn';
import { AI_FEATURE_COSTS } from '@/lib/credits/types';

interface StatusError extends Error {
  status?: number;
}

// POST /api/ai/enhance-image
// Calls Imagen or Hugging Face to generate/enhance listing images
export async function POST(request: Request) {
  try {
    const ctx = await requireRole('agent'); // Require agent role or above

    // Plan gate: AI requires Solo Pro or higher
    const gate = await checkPlanLimit(ctx, 'ai');
    if (!gate.allowed) return gateResponse(gate);

    const accountId = ctx.accountId;
    const supabase = ctx.supabase;

    // Fetch the showcase settings to check the preferred provider
    const { data: settings } = await supabase
      .from('showcase_settings')
      .select('flyer_ai_provider')
      .eq('account_id', accountId)
      .maybeSingle();

    const provider = settings?.flyer_ai_provider || 'huggingface';

    const body = await request.json().catch(() => null);
    if (!body || !body.prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const { prompt, aspectRatio = '1:1', image } = body;

    // Validate provider keys before burning credits
    if (provider === 'google') {
      if (!process.env.GEMINI_API_KEY) {
        return NextResponse.json(
          { error: 'GEMINI_API_KEY is not configured on the server.' },
          { status: 500 }
        );
      }
    } else {
      if (!process.env.HF_ACCESS_TOKEN) {
        return NextResponse.json(
          { error: 'HF_ACCESS_TOKEN is not configured on the server. Please add a free token from huggingface.co to your settings (.env.local).' },
          { status: 400 }
        );
      }
    }

    const cost = AI_FEATURE_COSTS.image_enhance;

    // Burn before the external call. Single flat cost regardless of
    // provider (Imagen vs HuggingFace) — no separate "full generation"
    // endpoint exists to justify pricing them differently.
    const burn = await burnCredits(accountId, 'image_enhance', cost, { client: supabase });
    if (!burn.success) {
      return NextResponse.json(
        {
          error: 'Insufficient credits for AI image enhancement.',
          creditsNeeded: cost,
          upgradeRequired: true,
        },
        { status: 402 },
      );
    }

    let imageResult: string;
    try {
      if (provider === 'google') {
        const apiKey = process.env.GEMINI_API_KEY;
        // Use Google AI Studio Imagen 4 predict URL format
        const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key=${apiKey}`;

        const payload = {
          instances: [
            {
              prompt: prompt,
            },
          ],
          parameters: {
            sampleCount: 1,
            aspectRatio: aspectRatio,
            outputMimeType: 'image/jpeg',
          },
        };

        console.log(`[Imagen AI] Requesting generation with prompt: "${prompt}"`);

        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        });

        if (!response.ok) {
          const errorData = await response.json().catch(() => ({}));
          const errMessage = errorData.error?.message || `Imagen API error: ${response.statusText}`;
          const err = new Error(errMessage) as StatusError;
          err.status = response.status;
          throw err;
        }

        const data = await response.json();
        const base64Bytes = data.predictions?.[0]?.bytesBase64Encoded;
        if (!base64Bytes) {
          console.error('[Imagen AI] No predictions or image bytes found in response:', data);
          throw new Error('No image was generated by the model.');
        }

        imageResult = `data:image/jpeg;base64,${base64Bytes}`;
      } else {
        // HUGGING FACE STABLE DIFFUSION (Free option)
        const hfToken = process.env.HF_ACCESS_TOKEN;
        console.log(`[HuggingFace AI] Requesting generation with prompt: "${prompt}"`);

        // Use FLUX.1-schnell as it is fully supported by Hugging Face's serverless Inference API (hf-inference)
        const url = 'https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell';
        const payload: Record<string, unknown> = { inputs: prompt };

        if (image) {
          console.log('[HuggingFace AI] Note: Image-to-image refinement is not supported by free serverless provider. Falling back to text-to-image using FLUX.1-schnell.');
        }

        const response = await fetch(url, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${hfToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        });

        if (!response.ok) {
          const errorText = await response.text().catch(() => '');
          let errMessage = `Hugging Face API error: ${response.statusText}`;
          let isWarmup = false;
          let estimatedTime = 0;
          try {
            const errorData = JSON.parse(errorText);
            errMessage = errorData.error || errMessage;
            if (response.status === 503 && errorData.estimated_time) {
              isWarmup = true;
              estimatedTime = errorData.estimated_time;
            }
          } catch {}
          if (isWarmup) {
            const err = new Error(`Hugging Face AI model is warming up. Please try again in ${Math.round(estimatedTime)} seconds.`) as StatusError;
            err.status = 503;
            throw err;
          }
          const err = new Error(errMessage) as StatusError;
          err.status = response.status;
          throw err;
        }

        const buffer = await response.arrayBuffer();
        const base64Bytes = Buffer.from(buffer).toString('base64');
        imageResult = `data:image/jpeg;base64,${base64Bytes}`;
      }
    } catch (apiErr: unknown) {
      // API or network failure: refund the credits
      await refundCredits(accountId, 'image_enhance', cost, { client: supabase });
      const err = apiErr as StatusError;
      console.error('[AI Enhance] API call failed, refunded credits. Error:', err.message);
      const status = err.status || 500;
      return NextResponse.json({ error: err.message || 'AI generation failed' }, { status });
    }

    return NextResponse.json({
      image: imageResult,
    });
  } catch (err: unknown) {
    console.error('[AI Enhance] Exception:', err);
    return toErrorResponse(err);
  }
}
