// ============================================================
// AI image generation — shared by the flyer creator and the
// greetings card. Two providers:
//
//   - Google Gemini image model (gemini-3.1-flash-image, aka "Nano
//     Banana") — paid, current, the provider the flyer UI is branded
//     around. It replaced the Imagen 4 `:predict` models, which Google
//     deprecated (imagen-4.0-* shut down 2026-08-17 and are already
//     unavailable to new API users). The model is env-overridable via
//     GEMINI_IMAGE_MODEL in case Google renames it again.
//   - Hugging Face — the free option. HF retired text-to-image
//     from their own `hf-inference` serverless ("deprecated and no
//     longer supported by provider hf-inference"), so we now call
//     the HF Inference Providers router (a live partner provider).
//     The endpoint is env-overridable because which provider a
//     token can route to varies per account.
//
// generateAiImage() honours the chosen provider but, when Hugging
// Face fails (e.g. the model/provider is unavailable), transparently
// falls back to Gemini if a Gemini key is configured — so the flyer
// still generates instead of hard-failing.
// ============================================================

export interface StatusError extends Error {
  status?: number;
}

function statusError(message: string, status: number): StatusError {
  const err = new Error(message) as StatusError;
  err.status = status;
  return err;
}

// HF router endpoint for the free image path. Defaults to FLUX.1-dev
// via fal-ai (higher quality than schnell, still a live provider on the
// HF router); override with HF_IMAGE_URL to point at whichever provider
// a given token can reach.
const HF_IMAGE_URL =
  process.env.HF_IMAGE_URL ||
  'https://router.huggingface.co/fal-ai/models/black-forest-labs/FLUX.1-dev';

// Gemini image model used for text-to-image. Defaults to the current
// replacement for the retired Imagen 4 models; override with
// GEMINI_IMAGE_MODEL if Google renames it.
const GEMINI_IMAGE_MODEL = process.env.GEMINI_IMAGE_MODEL || 'gemini-3.1-flash-image';

export async function generateWithImagen(
  prompt: string,
  aspectRatio: string,
  apiKey: string
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_IMAGE_MODEL}:generateContent?key=${apiKey}`;
  const payload = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      responseModalities: ['TEXT', 'IMAGE'],
      imageConfig: { aspectRatio },
    },
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw statusError(
      errorData.error?.message || `Gemini image API error: ${response.statusText}`,
      response.status
    );
  }

  const data = await response.json();
  const parts = data.candidates?.[0]?.content?.parts ?? [];
  const image = parts.find(
    (p: { inlineData?: { data?: string; mimeType?: string } }) => p.inlineData?.data
  )?.inlineData;
  if (!image?.data) {
    console.error('[Gemini image] No image bytes found in response:', JSON.stringify(data).slice(0, 500));
    throw statusError('No image was generated by the model.', 502);
  }
  return `data:${image.mimeType || 'image/png'};base64,${image.data}`;
}

export async function generateWithHuggingFace(prompt: string, token: string): Promise<string> {
  // Send both `inputs` (HF-normalized task input) and `prompt` (partner
  // provider native input) so the request works whichever shape the
  // routed provider expects; each ignores the key it doesn't use.
  const response = await fetch(HF_IMAGE_URL, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'image/png',
    },
    body: JSON.stringify({ inputs: prompt, prompt }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => '');
    let errMessage = `Hugging Face API error: ${response.statusText}`;
    try {
      const errorData = JSON.parse(errorText);
      // Warm-up: the model is loading, ask the caller to retry.
      if (response.status === 503 && errorData.estimated_time) {
        throw statusError(
          `Hugging Face AI model is warming up. Please try again in ${Math.round(errorData.estimated_time)} seconds.`,
          503
        );
      }
      errMessage = errorData.error?.message || errorData.error || errMessage;
    } catch (e) {
      if ((e as StatusError).status === 503) throw e;
      if (errorText) errMessage = errorText;
    }
    throw statusError(errMessage, response.status);
  }

  // The router returns either raw image bytes (HF-normalized route) or a
  // JSON envelope carrying a base64 image or a URL (partner-native route).
  const contentType = response.headers.get('content-type') || '';
  if (contentType.startsWith('image/')) {
    const buffer = await response.arrayBuffer();
    return `data:${contentType.split(';')[0]};base64,${Buffer.from(buffer).toString('base64')}`;
  }

  const data = await response.json().catch(() => null);
  const b64 =
    data?.data?.[0]?.b64_json ||
    data?.images?.[0]?.b64_json ||
    (typeof data?.image === 'string' ? data.image : null);
  if (b64) return `data:image/jpeg;base64,${b64}`;

  const imageUrl =
    data?.images?.[0]?.url ||
    data?.data?.[0]?.url ||
    data?.image?.url ||
    (typeof data?.output?.[0] === 'string' ? data.output[0] : null);
  if (imageUrl) {
    const imgRes = await fetch(imageUrl);
    if (!imgRes.ok) throw statusError('Hugging Face image URL could not be fetched.', 502);
    const buffer = await imgRes.arrayBuffer();
    const ct = (imgRes.headers.get('content-type') || 'image/jpeg').split(';')[0];
    return `data:${ct};base64,${Buffer.from(buffer).toString('base64')}`;
  }

  throw statusError('Hugging Face returned no image.', 502);
}

// Stability AI Stable Image models. sd3.5-* hit the /sd3 endpoint (the
// `model` field selects the variant); `ultra` hits the dedicated /ultra
// endpoint. Default is env-overridable via STABILITY_MODEL.
export const STABILITY_MODELS = [
  'sd3.5-large',
  'sd3.5-large-turbo',
  'sd3.5-medium',
  'ultra',
] as const;
const DEFAULT_STABILITY_MODEL = process.env.STABILITY_MODEL || 'sd3.5-large';

// Stability only accepts a fixed set of aspect ratios; map the ones our
// callers use that it doesn't support to the closest allowed value.
const STABILITY_ASPECTS = new Set([
  '16:9', '1:1', '21:9', '2:3', '3:2', '4:5', '5:4', '9:16', '9:21',
]);
function stabilityAspect(aspectRatio: string): string {
  if (STABILITY_ASPECTS.has(aspectRatio)) return aspectRatio;
  if (aspectRatio === '4:3') return '3:2';
  if (aspectRatio === '3:4') return '2:3';
  return '1:1';
}

export async function generateWithStability(
  prompt: string,
  aspectRatio: string,
  apiKey: string,
  model: string = DEFAULT_STABILITY_MODEL
): Promise<string> {
  const useUltra = model === 'ultra';
  const endpoint = useUltra
    ? 'https://api.stability.ai/v2beta/stable-image/generate/ultra'
    : 'https://api.stability.ai/v2beta/stable-image/generate/sd3';

  const form = new FormData();
  form.append('prompt', prompt);
  form.append('aspect_ratio', stabilityAspect(aspectRatio));
  form.append('output_format', 'png');
  if (!useUltra) form.append('model', model);

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}`, Accept: 'image/*' },
    body: form,
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => '');
    let message = `Stability API error: ${response.statusText}`;
    try {
      const errorData = JSON.parse(errorText);
      message =
        (Array.isArray(errorData.errors) ? errorData.errors.join('; ') : null) ||
        errorData.error ||
        errorData.message ||
        message;
    } catch {
      if (errorText) message = errorText;
    }
    throw statusError(message, response.status);
  }

  const buffer = await response.arrayBuffer();
  const contentType = (response.headers.get('content-type') || 'image/png').split(';')[0];
  return `data:${contentType};base64,${Buffer.from(buffer).toString('base64')}`;
}

export interface GenerateAiImageOptions {
  prompt: string;
  aspectRatio?: string;
  provider: 'google' | 'huggingface' | 'stability';
  stabilityModel?: string;
}

/**
 * Generate an image with the chosen provider. When the Hugging Face
 * (free) path fails and a Gemini key exists, transparently falls back
 * to the Gemini image model so the caller still gets an image. Throws a
 * StatusError when no configured provider can produce one.
 */
export async function generateAiImage(opts: GenerateAiImageOptions): Promise<string> {
  const { prompt, aspectRatio = '1:1', provider, stabilityModel } = opts;
  const geminiKey = process.env.GEMINI_API_KEY;
  const stabilityKey = process.env.STABILITY_API_KEY;

  if (provider === 'google') {
    if (!geminiKey) throw statusError('GEMINI_API_KEY is not configured on the server.', 500);
    return generateWithImagen(prompt, aspectRatio, geminiKey);
  }

  if (provider === 'stability') {
    if (!stabilityKey) throw statusError('STABILITY_API_KEY is not configured on the server.', 500);
    try {
      return await generateWithStability(prompt, aspectRatio, stabilityKey, stabilityModel);
    } catch (stErr) {
      if (geminiKey) {
        console.warn(
          '[image-gen] Stability path failed, falling back to Gemini:',
          (stErr as Error).message
        );
        return generateWithImagen(prompt, aspectRatio, geminiKey);
      }
      throw stErr;
    }
  }

  // Hugging Face (free) — fall back to Gemini, then Stability, if a key
  // for either is configured, so the flyer still gets an image.
  const hfToken = process.env.HF_ACCESS_TOKEN;
  try {
    if (!hfToken) throw statusError('HF_ACCESS_TOKEN is not configured on the server.', 400);
    return await generateWithHuggingFace(prompt, hfToken);
  } catch (hfErr) {
    if (geminiKey) {
      console.warn(
        '[image-gen] Hugging Face path failed, falling back to Gemini:',
        (hfErr as Error).message
      );
      return generateWithImagen(prompt, aspectRatio, geminiKey);
    }
    if (stabilityKey) {
      console.warn(
        '[image-gen] Hugging Face path failed, falling back to Stability:',
        (hfErr as Error).message
      );
      return generateWithStability(prompt, aspectRatio, stabilityKey, stabilityModel);
    }
    throw hfErr;
  }
}
