// ============================================================
// AI image generation — shared by the flyer creator and the
// greetings card. Two providers:
//
//   - Google Imagen 4 (imagen-4.0-generate-001) — paid, current,
//     the provider the flyer UI is branded around.
//   - Hugging Face — the free option. HF retired text-to-image
//     from their own `hf-inference` serverless ("deprecated and no
//     longer supported by provider hf-inference"), so we now call
//     the HF Inference Providers router (a live partner provider).
//     The endpoint is env-overridable because which provider a
//     token can route to varies per account.
//
// generateAiImage() honours the chosen provider but, when Hugging
// Face fails (e.g. the model/provider is unavailable), transparently
// falls back to Imagen if a Gemini key is configured — so the flyer
// still generates instead of hard-failing.
// ============================================================

export interface StatusError extends Error {
  status?: number;
}

function statusError(message: string, status: number): StatusError {
  const err = new Error(message) as StatusError;
  err.status = status;
  return err;
}

// HF router endpoint for the free image path. Defaults to FLUX.1-schnell
// via fal-ai (a live provider on the HF router); override with
// HF_IMAGE_URL to point at whichever provider a given token can reach.
const HF_IMAGE_URL =
  process.env.HF_IMAGE_URL ||
  'https://router.huggingface.co/fal-ai/models/black-forest-labs/FLUX.1-schnell';

export async function generateWithImagen(
  prompt: string,
  aspectRatio: string,
  apiKey: string
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key=${apiKey}`;
  const payload = {
    instances: [{ prompt }],
    parameters: {
      sampleCount: 1,
      aspectRatio,
      outputMimeType: 'image/jpeg',
    },
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw statusError(
      errorData.error?.message || `Imagen API error: ${response.statusText}`,
      response.status
    );
  }

  const data = await response.json();
  const base64Bytes = data.predictions?.[0]?.bytesBase64Encoded;
  if (!base64Bytes) {
    console.error('[Imagen AI] No predictions or image bytes found in response:', data);
    throw statusError('No image was generated by the model.', 502);
  }
  return `data:image/jpeg;base64,${base64Bytes}`;
}

export async function generateWithHuggingFace(prompt: string, token: string): Promise<string> {
  // Send both `inputs` (HF-normalized task input) and `prompt` (partner
  // provider native input) so the request works whichever shape the
  // routed provider expects; each ignores the key it doesn't use.
  const response = await fetch(HF_IMAGE_URL, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'image/png',
    },
    body: JSON.stringify({ inputs: prompt, prompt }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => '');
    let errMessage = `Hugging Face API error: ${response.statusText}`;
    try {
      const errorData = JSON.parse(errorText);
      // Warm-up: the model is loading, ask the caller to retry.
      if (response.status === 503 && errorData.estimated_time) {
        throw statusError(
          `Hugging Face AI model is warming up. Please try again in ${Math.round(errorData.estimated_time)} seconds.`,
          503
        );
      }
      errMessage = errorData.error?.message || errorData.error || errMessage;
    } catch (e) {
      if ((e as StatusError).status === 503) throw e;
      if (errorText) errMessage = errorText;
    }
    throw statusError(errMessage, response.status);
  }

  // The router returns either raw image bytes (HF-normalized route) or a
  // JSON envelope carrying a base64 image or a URL (partner-native route).
  const contentType = response.headers.get('content-type') || '';
  if (contentType.startsWith('image/')) {
    const buffer = await response.arrayBuffer();
    return `data:${contentType.split(';')[0]};base64,${Buffer.from(buffer).toString('base64')}`;
  }

  const data = await response.json().catch(() => null);
  const b64 =
    data?.data?.[0]?.b64_json ||
    data?.images?.[0]?.b64_json ||
    (typeof data?.image === 'string' ? data.image : null);
  if (b64) return `data:image/jpeg;base64,${b64}`;

  const imageUrl =
    data?.images?.[0]?.url ||
    data?.data?.[0]?.url ||
    data?.image?.url ||
    (typeof data?.output?.[0] === 'string' ? data.output[0] : null);
  if (imageUrl) {
    const imgRes = await fetch(imageUrl);
    if (!imgRes.ok) throw statusError('Hugging Face image URL could not be fetched.', 502);
    const buffer = await imgRes.arrayBuffer();
    const ct = (imgRes.headers.get('content-type') || 'image/jpeg').split(';')[0];
    return `data:${ct};base64,${Buffer.from(buffer).toString('base64')}`;
  }

  throw statusError('Hugging Face returned no image.', 502);
}

export interface GenerateAiImageOptions {
  prompt: string;
  aspectRatio?: string;
  provider: 'google' | 'huggingface';
}

/**
 * Generate an image with the chosen provider. When the Hugging Face
 * (free) path fails and a Gemini key exists, transparently falls back
 * to Imagen so the caller still gets an image. Throws a StatusError
 * when no configured provider can produce one.
 */
export async function generateAiImage(opts: GenerateAiImageOptions): Promise<string> {
  const { prompt, aspectRatio = '1:1', provider } = opts;
  const geminiKey = process.env.GEMINI_API_KEY;

  if (provider === 'google') {
    if (!geminiKey) throw statusError('GEMINI_API_KEY is not configured on the server.', 500);
    return generateWithImagen(prompt, aspectRatio, geminiKey);
  }

  const hfToken = process.env.HF_ACCESS_TOKEN;
  try {
    if (!hfToken) throw statusError('HF_ACCESS_TOKEN is not configured on the server.', 400);
    return await generateWithHuggingFace(prompt, hfToken);
  } catch (hfErr) {
    if (geminiKey) {
      console.warn(
        '[image-gen] Hugging Face path failed, falling back to Imagen:',
        (hfErr as Error).message
      );
      return generateWithImagen(prompt, aspectRatio, geminiKey);
    }
    throw hfErr;
  }
}
