ALTER TABLE guidance_value_rates
  ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS guidance_value_rates_source_order_idx
  ON guidance_value_rates (source_id, page DESC, seq DESC);
